services:
  api:
    build: .
    container_name: classmate-api
    ports:
      - '3000:3000'
    env_file:
      - .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - classmate-network

networks:
  classmate-network:
    driver: bridge
