/**
 * Standardized Application Error Codes
 * Used by the AllExceptionsFilter and the frontend for programmatic handling.
 */
export const ERROR_CODES = {
  INFRA: {
    INPUT_VALIDATION: 'INPUT_VALIDATION',
    ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
    SERVER_ERROR: 'SERVER_ERROR',
    INPUT_TYPE_MISMATCH: 'INPUT_TYPE_MISMATCH',
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    DUPLICATE_KEY: 'DUPLICATE_KEY',
    DRIZZLE_QUERY_ERROR: 'DRIZZLE_QUERY_ERROR',
    FORBIDDEN: 'FORBIDDEN',
    BAD_REQUEST: 'BAD_REQUEST',
  },

  AUTH: {
    ROLE_NOT_ASSIGNED: 'AUTH_ROLE_NOT_ASSIGNED',
    ROLE_PENDING: 'AUTH_ROLE_PENDING',
  },

  COURSE: {
    NOT_FOUND: 'COURSE_NOT_FOUND',
    CAPACITY_FULL: 'COURSE_CAPACITY_FULL',
    ALREADY_ENROLLED: 'COURSE_ALREADY_ENROLLED',
  },

  ORGANIZATION: {
    ACCESS_DENIED: 'ORGANIZATION_ACCESS_DENIED',
  },

  TEACHER: {
    NOT_FOUND_IN_ORG: 'TEACHER_NOT_FOUND_IN_ORG',
  },

  ATTENDANCE: {
    NOT_MEMBER: 'ATTENDANCE_STUDENT_NOT_MEMBER',
    FUTURE_DATE: 'ATTENDANCE_FUTURE_DATE',
    NOT_AUTHORIZED: 'ATTENDANCE_NOT_AUTHORIZED',
  },
} as const;
